name: difygram
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: GeorgeStrakhov/DifyGram
  envs:
    - key: BOT_TOKEN
      scope: RUN_TIME
    - key: DIFY_API_KEY
      scope: RUN_TIME
  name: difygram
  run_command: python -m src.bot
